# Generated by Django 3.2.4 on 2022-01-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('prayer_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('prayer_request_date', models.DateTimeField(verbose_name='prayer request date')),
                ('prayer_answer_date', models.DateTimeField(blank=True, null=True, verbose_name='prayer answer date')),
                ('prayer_description', models.CharField(max_length=1000)),
                ('prayer_recipients', models.CharField(blank=True, max_length=100, null=True)),
                ('prayer_recipients_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('prayer_categories', models.CharField(choices=[('thanks', 'Thanksgviing'), ('healing', 'Healing'), ('trauma', 'Trauma'), ('conversion', 'Conversion'), ('belief', 'Belief'), ('strength', 'Strength'), ('leaders', 'Leaders'), ('needs', 'Needs'), ('forgiveness', 'Forgiveness')], default=['thanks', 'Thanksgiving'], max_length=100)),
                ('prayer_answered', models.BooleanField()),
                ('prayer_updates', models.CharField(blank=True, max_length=1400, null=True)),
                ('prayer_image', models.ImageField(blank=True, null=True, upload_to='prayer_images/%Y/%m/%d')),
                ('prayer_answered_image', models.ImageField(blank=True, null=True, upload_to='answered_prayer_images/%Y/%m/%d')),
            ],
        ),
    ]
