# Generated by Django 3.2.4 on 2022-01-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayerrequest', '0002_alter_prayer_prayer_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prayer',
            name='prayer_categories',
        ),
        migrations.AlterField(
            model_name='prayer',
            name='prayer_request_date',
            field=models.DateTimeField(auto_now=True, verbose_name='prayer request date'),
        ),
    ]
