# Generated by Django 3.2.4 on 2022-01-28 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayerrequest', '0003_auto_20220122_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayer',
            name='prayer_count',
            field=models.IntegerField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
