# Generated by Django 3.2.4 on 2022-01-22 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayerboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayer',
            name='prayer_categories',
            field=models.CharField(choices=[('thanks', 'Thanksgiving'), ('healing', 'Healing'), ('trauma', 'Trauma'), ('conversion', 'Conversion'), ('belief', 'Belief'), ('strength', 'Strength'), ('leaders', 'Leaders'), ('needs', 'Needs'), ('forgiveness', 'Forgiveness')], default=['thanks', 'Thanksgiving'], max_length=100),
        ),
    ]
