# Generated by Django 3.2.4 on 2022-01-28 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayerboard', '0003_remove_prayer_prayer_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayer',
            name='prayer_count',
            field=models.IntegerField(default=1, editable=False, verbose_name='prayer count'),
            preserve_default=False,
        ),
    ]
