# Generated by Django 3.2.4 on 2022-02-04 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayerboard', '0005_alter_prayer_prayer_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayer',
            name='prayer_count',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
