# Generated by Django 3.2.4 on 2022-01-01 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('prayer_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('prayer_request_date', models.DateTimeField(verbose_name='prayer request date')),
                ('prayer_answer_date', models.DateTimeField(verbose_name='prayer answer date')),
                ('prayer_description', models.CharField(max_length=1000)),
                ('prayer_recipients', models.CharField(max_length=100)),
                ('prayer_categories', models.CharField(max_length=200)),
                ('prayer_answered', models.BooleanField()),
                ('prayer_updates', models.CharField(max_length=1400)),
            ],
        ),
    ]
