# Generated by Django 3.2.4 on 2022-01-01 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayerrequests', '0003_auto_20220101_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayer',
            name='prayer_answer_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='prayer answer date'),
        ),
        migrations.AlterField(
            model_name='prayer',
            name='prayer_categories',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='prayer',
            name='prayer_updates',
            field=models.CharField(blank=True, max_length=1400, null=True),
        ),
    ]
