# Generated by Django 3.2.4 on 2022-01-14 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayerrequests', '0004_auto_20220101_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayer',
            name='prayer_answered_image',
            field=models.ImageField(blank=True, null=True, upload_to='answered_prayer_images/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='prayer',
            name='prayer_image',
            field=models.ImageField(blank=True, null=True, upload_to='prayer_images/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='prayer',
            name='prayer_recipients_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prayer',
            name='prayer_categories',
            field=models.CharField(choices=[('thanks', 'Thanksgviing'), ('healing', 'Healing'), ('trauma', 'Trauma'), ('conversion', 'Conversion'), ('belief', 'Belief'), ('strength', 'Strength'), ('leaders', 'Leaders'), ('needs', 'Needs'), ('forgiveness', 'Forgiveness')], default=['thanks', 'Thanksgiving'], max_length=100),
        ),
        migrations.AlterField(
            model_name='prayer',
            name='prayer_recipients',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
